title: "Jamalam's Blog"
author: "Jamalam"
description: "Random Rantings of an Amateur Software Developer" # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

baseurl: "/blog"

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "jamalamisadev@gmail.com"
#twitter_username: "twitteruser"
github_username: "Jamalam360"
#linkedin_username: "linkedinuser"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
theme: "minima"

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
